### ISSUE TITLE
Statt Anzahl Zellen eine Voll-Spannung angeben

### ISSUE THREAD

**Issue by DerDoubleD** [nichtgedacht/AltGraph#1]
Ist es möglich statt Anzahl Zellen eine Voll-Spannung anzugeben.
Dann wäre man flexibler bei den Zellentypen. (LiPo, LiFe, LiOn)

**Comment by nichtgedacht** [comment]
Die einstellbare Warnspannung und die einstellbare Anzahl der Zellen ermöglichen dem Script die Unterscheidung zwischen LiPo und NiMh Zellen. Die Anzeige des Batteriefüllstands geht je nach nach diesen beiden Zellchemien über zwei verschiedene Lookup Tabellen. Da sich die LiFe und LiIon Zellspannung nicht so sehr von LiPo unterscheiden würde hier auch Lipo angenommen und die Füllstandsanzeige ginge entsprechend falsch, aber die Warnschwelle an sich bliebe ja korrekt. Das Script wertet aktuell ja nur die Spannung vom Empfänger aus und ist daher so nur für reine Segelflugzeuge vorgesehen und deckt damit meinen persönlichen Bedarf ab. Da alles nur Text ist, kannst Du es ja nach Deinem Geschmack verändern und einen Pullrequest machen. Für Elektrosegler mit Empfänger am BEC müsste ein weiterer Sensorwert (Spannung vom Antriebsakku) auswählbar gemacht werden und der Wert in Screen.lua statt der Empfängerspannung ausgewertet/angezeigt werden.
